package esi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

// Summary is the compact per-character view for the overview page.
type Summary struct {
	Wallet      float64
	TotalSP     int64
	SolarSystem string
	Location    string // station/structure name when docked, "" in space
	Ship        string
	ShipName    string
	Online      bool
	QueueSkill  string // currently training skill, "" if queue empty
	QueueLevel  int
	QueueEnds   time.Time
	Errors      []string
}

func (c *Client) Summary(characterID int64) Summary {
	var s Summary

	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/wallet/", characterID), &s.Wallet); err != nil {
		s.Errors = append(s.Errors, fmt.Sprintf("wallet: %v", err))
	}

	var skills struct {
		TotalSP int64 `json:"total_sp"`
	}
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/skills/", characterID), &skills); err != nil {
		s.Errors = append(s.Errors, fmt.Sprintf("skills: %v", err))
	}
	s.TotalSP = skills.TotalSP

	var loc struct {
		SolarSystemID int64 `json:"solar_system_id"`
		StationID     int64 `json:"station_id"`
		StructureID   int64 `json:"structure_id"`
	}
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/location/", characterID), &loc); err != nil {
		s.Errors = append(s.Errors, fmt.Sprintf("location: %v", err))
	}

	var ship struct {
		ShipTypeID int64  `json:"ship_type_id"`
		ShipName   string `json:"ship_name"`
	}
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/ship/", characterID), &ship); err != nil {
		s.Errors = append(s.Errors, fmt.Sprintf("ship: %v", err))
	}
	s.ShipName = cleanPyString(ship.ShipName)

	var online struct {
		Online bool `json:"online"`
	}
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/online/", characterID), &online); err != nil {
		s.Errors = append(s.Errors, fmt.Sprintf("online: %v", err))
	}
	s.Online = online.Online

	queue, err := c.SkillQueue(characterID)
	if err != nil {
		s.Errors = append(s.Errors, fmt.Sprintf("queue: %v", err))
	}
	now := time.Now()
	for _, q := range queue {
		if q.FinishDate.After(now) {
			s.QueueSkill = q.SkillName
			s.QueueLevel = q.FinishedLevel
			s.QueueEnds = q.FinishDate
			break
		}
	}

	ids := []int64{loc.SolarSystemID, ship.ShipTypeID}
	if loc.StationID != 0 {
		ids = append(ids, loc.StationID)
	}
	names := c.Names(ids)
	s.SolarSystem = names[loc.SolarSystemID]
	s.Ship = names[ship.ShipTypeID]
	switch {
	case loc.StationID != 0:
		s.Location = names[loc.StationID]
	case loc.StructureID != 0:
		// structures never resolve via /universe/names/ — authorized endpoint only
		var st struct {
			Name string `json:"name"`
		}
		if _, err := c.get(characterID, fmt.Sprintf("/universe/structures/%d/", loc.StructureID), &st); err == nil && st.Name != "" {
			s.Location = st.Name
		} else {
			s.Location = fmt.Sprintf("Структура %d", loc.StructureID)
		}
	}
	return s
}

// Online reports whether the character is currently logged in.
func (c *Client) Online(characterID int64) (bool, error) {
	var online struct {
		Online bool `json:"online"`
	}
	_, err := c.get(characterID, fmt.Sprintf("/characters/%d/online/", characterID), &online)
	return online.Online, err
}

// cleanPyString fixes CCP's autogenerated ship names which arrive as a
// Python repr: u'Capsule\xa0— Pilot Name'.
func cleanPyString(s string) string {
	if !strings.HasPrefix(s, "u'") || !strings.HasSuffix(s, "'") || len(s) < 3 {
		return s
	}
	inner := s[2 : len(s)-1]
	var b strings.Builder
	for i := 0; i < len(inner); {
		if inner[i] != '\\' || i+1 >= len(inner) {
			b.WriteByte(inner[i])
			i++
			continue
		}
		switch inner[i+1] {
		case 'x':
			if i+4 <= len(inner) {
				if n, err := strconv.ParseUint(inner[i+2:i+4], 16, 32); err == nil {
					b.WriteRune(rune(n))
					i += 4
					continue
				}
			}
		case 'u':
			if i+6 <= len(inner) {
				if n, err := strconv.ParseUint(inner[i+2:i+6], 16, 32); err == nil {
					b.WriteRune(rune(n))
					i += 6
					continue
				}
			}
		case '\\', '\'':
			b.WriteByte(inner[i+1])
			i += 2
			continue
		}
		b.WriteByte(inner[i])
		i++
	}
	return b.String()
}

// ── skills ───────────────────────────────────────────────────────────

type QueueEntry struct {
	SkillID         int64     `json:"skill_id"`
	SkillName       string    `json:"-"`
	FinishedLevel   int       `json:"finished_level"`
	FinishDate      time.Time `json:"finish_date"`
	StartDate       time.Time `json:"start_date"`
	Position        int       `json:"queue_position"`
	TrainingStartSP int64     `json:"training_start_sp"`
	LevelStartSP    int64     `json:"level_start_sp"`
	LevelEndSP      int64     `json:"level_end_sp"`
}

func (c *Client) SkillQueue(characterID int64) ([]QueueEntry, error) {
	var queue []QueueEntry
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/skillqueue/", characterID), &queue); err != nil {
		return nil, err
	}
	ids := make([]int64, len(queue))
	for i, q := range queue {
		ids[i] = q.SkillID
	}
	names := c.typeNamesLocalized(ids)
	for i := range queue {
		queue[i].SkillName = names[queue[i].SkillID]
	}
	return queue, nil
}

// Skill is one entry of the full character skill sheet.
type Skill struct {
	SkillID      int64  `json:"skill_id"`
	SkillName    string `json:"-"`
	ActiveLevel  int    `json:"active_skill_level"`
	TrainedLevel int    `json:"trained_skill_level"`
	Skillpoints  int64  `json:"skillpoints_in_skill"`
}

type SkillSheet struct {
	Skills        []Skill `json:"skills"`
	TotalSP       int64   `json:"total_sp"`
	UnallocatedSP int64   `json:"unallocated_sp"`
}

// Skills returns the full skill list with resolved names, sorted by name.
func (c *Client) Skills(characterID int64) (*SkillSheet, error) {
	var sheet SkillSheet
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/skills/", characterID), &sheet); err != nil {
		return nil, err
	}
	ids := make([]int64, len(sheet.Skills))
	for i, s := range sheet.Skills {
		ids[i] = s.SkillID
	}
	names := c.typeNamesLocalized(ids)
	for i := range sheet.Skills {
		sheet.Skills[i].SkillName = names[sheet.Skills[i].SkillID]
	}
	sort.Slice(sheet.Skills, func(i, j int) bool {
		return sheet.Skills[i].SkillName < sheet.Skills[j].SkillName
	})
	return &sheet, nil
}

// TreeSkill is one skill inside a group tree: trained by the character
// (Known) or merely existing in game.
type TreeSkill struct {
	Skill
	Known bool
}

// SkillGroupTree is one in-game skill group with every published skill
// in it; the character's trained ones are marked Known.
type SkillGroupTree struct {
	Name    string
	Skills  []TreeSkill
	Known   int
	GroupSP int64
}

const skillCategoryID = 16

// typeInfo is the localized subset of /universe/types/{id}/.
type typeInfo struct {
	Name      string `json:"name"`
	Published bool   `json:"published"`
}

// typeInfos resolves type name + published per id via /universe/types/
// — unlike the batch /universe/names/ this endpoint is localized.
// Failures are simply absent from the result (callers fall back to the
// batch resolver). Static data: cached per language after first load.
func (c *Client) typeInfos(ids []int64) map[int64]typeInfo {
	out := make(map[int64]typeInfo, len(ids))
	var mu sync.Mutex
	sem := make(chan struct{}, 8)
	var wg sync.WaitGroup
	for _, id := range dedupe(ids) {
		if id == 0 {
			continue
		}
		wg.Add(1)
		go func(id int64) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()
			var ti typeInfo
			if _, err := c.get(0, fmt.Sprintf("/universe/types/%d/", id), &ti); err == nil {
				mu.Lock()
				out[id] = ti
				mu.Unlock()
			}
		}(id)
	}
	wg.Wait()
	return out
}

// typeNamesLocalized names the given type ids via typeInfos, falling
// back to the English batch resolver for anything that failed.
func (c *Client) typeNamesLocalized(ids []int64) map[int64]string {
	out := make(map[int64]string, len(ids))
	var missing []int64
	for id, ti := range c.typeInfos(ids) {
		if ti.Name != "" {
			out[id] = ti.Name
		}
	}
	for _, id := range dedupe(ids) {
		if _, ok := out[id]; !ok && id != 0 {
			missing = append(missing, id)
		}
	}
	if len(missing) > 0 {
		for id, n := range c.Names(missing) {
			out[id] = n
		}
	}
	return out
}

// SkillTree groups the character's trained skills by in-game skill
// group (universe category 16). Group composition is static and cached.
func (c *Client) SkillTree(sheet *SkillSheet) ([]SkillGroupTree, error) {
	var cat struct {
		Groups []int64 `json:"groups"`
	}
	if _, err := c.get(0, fmt.Sprintf("/universe/categories/%d/", skillCategoryID), &cat); err != nil {
		return nil, err
	}

	type groupInfo struct {
		ID    int64
		Name  string  `json:"name"`
		Types []int64 `json:"types"`
	}
	infos := make([]groupInfo, len(cat.Groups))
	sem := make(chan struct{}, 8)
	var wg sync.WaitGroup
	for i, gid := range cat.Groups {
		wg.Add(1)
		go func(i int, gid int64) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()
			var gi groupInfo
			if _, err := c.get(0, fmt.Sprintf("/universe/groups/%d/", gid), &gi); err == nil {
				gi.ID = gid
				infos[i] = gi
			}
		}(i, gid)
	}
	wg.Wait()

	byType := map[int64]Skill{}
	for _, s := range sheet.Skills {
		byType[s.SkillID] = s
	}

	// Skills the character hasn't injected: resolve name + published flag
	// per type. Static data — after the first load it lives in the cache.
	var unknownIDs []int64
	for _, gi := range infos {
		for _, tid := range gi.Types {
			if _, ok := byType[tid]; !ok {
				unknownIDs = append(unknownIDs, tid)
			}
		}
	}
	unknown := c.typeInfos(unknownIDs)

	var tree []SkillGroupTree
	for _, gi := range infos {
		if gi.Name == "" {
			continue
		}
		node := SkillGroupTree{Name: gi.Name}
		for _, tid := range gi.Types {
			if s, ok := byType[tid]; ok {
				node.Skills = append(node.Skills, TreeSkill{Skill: s, Known: true})
				node.Known++
				node.GroupSP += s.Skillpoints
			} else if ti, ok := unknown[tid]; ok && ti.Published {
				node.Skills = append(node.Skills, TreeSkill{Skill: Skill{SkillID: tid, SkillName: ti.Name}})
			}
		}
		if len(node.Skills) > 0 {
			sort.Slice(node.Skills, func(i, j int) bool {
				return node.Skills[i].SkillName < node.Skills[j].SkillName
			})
			tree = append(tree, node)
		}
	}
	sort.Slice(tree, func(i, j int) bool { return tree[i].Name < tree[j].Name })
	return tree, nil
}

// ── blueprints owned by a character ──────────────────────────────────

// OwnedBlueprint is one blueprint stack in a hangar, with the research
// levels of that particular item.
type OwnedBlueprint struct {
	ItemID     int64  `json:"item_id"`
	TypeID     int64  `json:"type_id"`
	TypeName   string `json:"-"`
	LocationID int64  `json:"location_id"`
	Location   string `json:"-"`
	// quantity: -1 = original, -2 = copy, positive = stack of copies
	Quantity int64 `json:"quantity"`
	Runs     int64 `json:"runs"` // -1 for originals
	ME       int   `json:"material_efficiency"`
	TE       int   `json:"time_efficiency"`
}

// IsCopy reports whether this is a blueprint copy.
func (b *OwnedBlueprint) IsCopy() bool { return b.Quantity == -2 || b.Runs > 0 }

// CharacterBlueprints lists every blueprint the character owns
// (scope esi-characters.read_blueprints.v1), with names and locations.
func (c *Client) CharacterBlueprints(characterID int64) ([]OwnedBlueprint, error) {
	var all []OwnedBlueprint
	page := 1
	for {
		var chunk []OwnedBlueprint
		pages, err := c.get(characterID,
			fmt.Sprintf("/characters/%d/blueprints/?page=%d", characterID, page), &chunk)
		if err != nil {
			return nil, err
		}
		all = append(all, chunk...)
		if page >= pages {
			break
		}
		page++
	}

	typeIDs := make([]int64, 0, len(all))
	locIDs := make([]int64, 0, len(all))
	for _, b := range all {
		typeIDs = append(typeIDs, b.TypeID)
		locIDs = append(locIDs, b.LocationID)
	}
	names := c.typeNamesLocalized(typeIDs)
	locs := c.LocationNames(characterID, locIDs)
	for i := range all {
		all[i].TypeName = names[all[i].TypeID]
		if n := locs[all[i].LocationID]; n != "" {
			all[i].Location = n
		} else {
			// Blueprints inside containers/ships report that item as location.
			all[i].Location = "в контейнере"
		}
	}
	sort.Slice(all, func(i, j int) bool { return all[i].TypeName < all[j].TypeName })
	return all, nil
}

// ── planetary colonies ───────────────────────────────────────────────

// Colony is one planetary colony from /characters/{id}/planets/.
type Colony struct {
	LastUpdate    time.Time `json:"last_update"`
	NumPins       int       `json:"num_pins"`
	OwnerID       int64     `json:"owner_id"`
	PlanetID      int64     `json:"planet_id"`
	PlanetType    string    `json:"planet_type"`
	SolarSystemID int64     `json:"solar_system_id"`
	UpgradeLevel  int       `json:"upgrade_level"`
	// filled in by the caller
	PlanetName string `json:"-"`
	SystemName string `json:"-"`
}

func (c *Client) Colonies(characterID int64) ([]Colony, error) {
	var out []Colony
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/planets/", characterID), &out); err != nil {
		return nil, err
	}
	// Planet ids are NOT resolvable through /universe/names/ — including
	// one poisons the whole batch — so names come from the per-planet
	// endpoint while systems go through the batch resolver.
	sysIDs := make([]int64, 0, len(out))
	for _, col := range out {
		sysIDs = append(sysIDs, col.SolarSystemID)
	}
	names := c.Names(sysIDs)

	var wg sync.WaitGroup
	for i := range out {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			var p struct {
				Name string `json:"name"`
			}
			if _, err := c.get(0, fmt.Sprintf("/universe/planets/%d/", out[i].PlanetID), &p); err == nil {
				out[i].PlanetName = p.Name
			}
		}(i)
	}
	wg.Wait()

	for i := range out {
		out[i].SystemName = names[out[i].SolarSystemID]
		if out[i].PlanetName == "" {
			out[i].PlanetName = fmt.Sprintf("Планета %d", out[i].PlanetID)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].PlanetName < out[j].PlanetName })
	return out, nil
}

// ColonyPin is a structure inside a colony.
type ColonyPin struct {
	PinID          int64     `json:"pin_id"`
	TypeID         int64     `json:"type_id"`
	SchematicID    int64     `json:"schematic_id"`
	Latitude       float64   `json:"latitude"`
	Longitude      float64   `json:"longitude"`
	InstallTime    time.Time `json:"install_time"`
	ExpiryTime     time.Time `json:"expiry_time"`
	LastCycleStart time.Time `json:"last_cycle_start"`
	Contents       []struct {
		Amount int64 `json:"amount"`
		TypeID int64 `json:"type_id"`
	} `json:"contents"`
	ExtractorDetails *struct {
		CycleTime     int     `json:"cycle_time"`
		HeadRadius    float64 `json:"head_radius"`
		ProductTypeID int64   `json:"product_type_id"`
		QtyPerCycle   int64   `json:"qty_per_cycle"`
		Heads         []struct {
			HeadID    int     `json:"head_id"`
			Latitude  float64 `json:"latitude"`
			Longitude float64 `json:"longitude"`
		} `json:"heads"`
	} `json:"extractor_details"`
	FactoryDetails *struct {
		SchematicID int64 `json:"schematic_id"`
	} `json:"factory_details"`
}

// ColonyDetail is the full layout of one colony.
type ColonyDetail struct {
	Links []struct {
		DestinationPinID int64 `json:"destination_pin_id"`
		LinkLevel        int   `json:"link_level"`
		SourcePinID      int64 `json:"source_pin_id"`
	} `json:"links"`
	Pins   []ColonyPin `json:"pins"`
	Routes []struct {
		ContentTypeID    int64   `json:"content_type_id"`
		DestinationPinID int64   `json:"destination_pin_id"`
		Quantity         float64 `json:"quantity"`
		RouteID          int64   `json:"route_id"`
		SourcePinID      int64   `json:"source_pin_id"`
		Waypoints        []int64 `json:"waypoints"`
	} `json:"routes"`
}

func (c *Client) ColonyDetail(characterID, planetID int64) (*ColonyDetail, error) {
	var out ColonyDetail
	if _, err := c.get(characterID,
		fmt.Sprintf("/characters/%d/planets/%d/", characterID, planetID), &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// RawJSON fetches an arbitrary ESI path and returns the response body
// unchanged — used by the "raw API" view.
func (c *Client) RawJSON(characterID int64, path string) (json.RawMessage, error) {
	var raw json.RawMessage
	if _, err := c.get(characterID, path, &raw); err != nil {
		return nil, err
	}
	return raw, nil
}

// ── clones / implants / attributes ───────────────────────────────────

// Implants returns type ids of the implants plugged into the active clone.
func (c *Client) Implants(characterID int64) ([]int64, error) {
	var out []int64
	_, err := c.get(characterID, fmt.Sprintf("/characters/%d/implants/", characterID), &out)
	return out, err
}

type JumpClone struct {
	ID           int64   `json:"jump_clone_id"`
	Name         string  `json:"name"`
	LocationID   int64   `json:"location_id"`
	LocationType string  `json:"location_type"` // station | structure
	Implants     []int64 `json:"implants"`
}

type Clones struct {
	HomeLocation struct {
		LocationID   int64  `json:"location_id"`
		LocationType string `json:"location_type"`
	} `json:"home_location"`
	JumpClones        []JumpClone `json:"jump_clones"`
	LastCloneJump     time.Time   `json:"last_clone_jump_date"`
	LastStationChange time.Time   `json:"last_station_change_date"`
}

func (c *Client) CharacterClones(characterID int64) (*Clones, error) {
	var out Clones
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/clones/", characterID), &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type Attributes struct {
	Charisma          int       `json:"charisma"`
	Intelligence      int       `json:"intelligence"`
	Memory            int       `json:"memory"`
	Perception        int       `json:"perception"`
	Willpower         int       `json:"willpower"`
	BonusRemaps       int       `json:"bonus_remaps"`
	LastRemap         time.Time `json:"last_remap_date"`
	RemapCooldownEnds time.Time `json:"accrued_remap_cooldown_date"`
}

func (c *Client) CharacterAttributes(characterID int64) (*Attributes, error) {
	var out Attributes
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/attributes/", characterID), &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// LocationNames resolves station and structure ids to names: stations
// go through the public batch resolver, structures (id ≥ 1e12) need the
// authorized per-structure endpoint.
func (c *Client) LocationNames(characterID int64, ids []int64) map[int64]string {
	out := map[int64]string{}
	var stations []int64
	for _, id := range dedupe(ids) {
		if id == 0 {
			continue
		}
		if id >= 1_000_000_000_000 {
			var st struct {
				Name string `json:"name"`
			}
			if _, err := c.get(characterID, fmt.Sprintf("/universe/structures/%d/", id), &st); err == nil && st.Name != "" {
				out[id] = st.Name
			} else {
				out[id] = fmt.Sprintf("Структура %d", id)
			}
		} else {
			stations = append(stations, id)
		}
	}
	for id, n := range c.Names(stations) {
		out[id] = n
	}
	return out
}

// ── wallet ───────────────────────────────────────────────────────────

func (c *Client) WalletBalance(characterID int64) (float64, error) {
	var balance float64
	_, err := c.get(characterID, fmt.Sprintf("/characters/%d/wallet/", characterID), &balance)
	return balance, err
}

// JournalEntry is one wallet journal line.
//
// ID is the deduplication key: ESI keeps only a rolling window, so the
// accounting collector stores every line locally and must never post the
// same one twice.
//
// ContextID ties a line to what caused it, and its meaning changes with
// ContextIDType. GRABLE (verified 2026-08-24): only some ref_types carry it
// — market_transaction (transaction id) and contract_brokers_fee (contract
// id) do, while brokers_fee and transaction_tax have no context field at
// all and must be matched by time and amount instead.
type JournalEntry struct {
	ID            int64     `json:"id"`
	Date          time.Time `json:"date"`
	Amount        float64   `json:"amount"`
	Balance       float64   `json:"balance"`
	Description   string    `json:"description"`
	RefType       string    `json:"ref_type"`
	ContextID     int64     `json:"context_id"`
	ContextIDType string    `json:"context_id_type"` // market_transaction_id|
	// market_order_id|character_id|…
	FirstPartyID  int64   `json:"first_party_id"`
	SecondPartyID int64   `json:"second_party_id"`
	Reason        string  `json:"reason"`
	Tax           float64 `json:"tax"`
	TaxReceiverID int64   `json:"tax_receiver_id"`
}

// WalletJournal returns the character's journal, all pages. ESI serves
// 2500 lines per page and keeps roughly 30 days.
func (c *Client) WalletJournal(characterID int64) ([]JournalEntry, error) {
	var out []JournalEntry
	for page := 1; ; page++ {
		var chunk []JournalEntry
		pages, err := c.get(characterID,
			fmt.Sprintf("/characters/%d/wallet/journal/?page=%d", characterID, page), &chunk)
		if err != nil {
			return out, err
		}
		out = append(out, chunk...)
		if page >= pages {
			return out, nil
		}
	}
}

// Transaction is one market fill.
//
// TransactionID deduplicates it; JournalRefID points at the wallet journal
// line of the same fill, which is how a sale is tied to its sales tax.
// The broker fee is NOT here at all — see JournalEntry.
type Transaction struct {
	TransactionID int64     `json:"transaction_id"`
	JournalRefID  int64     `json:"journal_ref_id"`
	ClientID      int64     `json:"client_id"`
	IsPersonal    bool      `json:"is_personal"`
	Date          time.Time `json:"date"`
	IsBuy         bool      `json:"is_buy"`
	Quantity      int64     `json:"quantity"`
	TypeID        int64     `json:"type_id"`
	TypeName      string    `json:"-"`
	UnitPrice     float64   `json:"unit_price"`
	LocationID    int64     `json:"location_id"`
	LocationName  string    `json:"-"`
}

// Total is the full transaction amount for display.
func (t *Transaction) Total() float64 { return t.UnitPrice * float64(t.Quantity) }

func (c *Client) WalletTransactions(characterID int64) ([]Transaction, error) {
	var out []Transaction
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/wallet/transactions/", characterID), &out); err != nil {
		return nil, err
	}
	var ids []int64
	for _, t := range out {
		ids = append(ids, t.TypeID, t.LocationID)
	}
	names := c.Names(ids)
	for i := range out {
		out[i].TypeName = names[out[i].TypeID]
		out[i].LocationName = names[out[i].LocationID]
	}
	return out, nil
}

// LoyaltyRow is the character's loyalty points with one NPC corporation.
type LoyaltyRow struct {
	CorporationID int64  `json:"corporation_id"`
	Points        int64  `json:"loyalty_points"`
	CorpName      string `json:"-"`
}

func (c *Client) Loyalty(characterID int64) ([]LoyaltyRow, error) {
	var out []LoyaltyRow
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/loyalty/points/", characterID), &out); err != nil {
		return nil, err
	}
	ids := make([]int64, len(out))
	for i, l := range out {
		ids[i] = l.CorporationID
	}
	names := c.Names(ids)
	for i := range out {
		out[i].CorpName = names[out[i].CorporationID]
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Points > out[j].Points })
	return out, nil
}

// MarketPrice is the global reference price CCP publishes per type:
// AdjustedPrice drives industry job cost, AveragePrice is the "estimated
// value" the client shows on item cards.
type MarketPrice struct {
	TypeID   int64   `json:"type_id"`
	Adjusted float64 `json:"adjusted_price"`
	Average  float64 `json:"average_price"`
}

// MarketPrices returns global reference prices keyed by type id.
// One request for ~16k types, cached by ESI for about an hour.
func (c *Client) MarketPrices() (map[int64]MarketPrice, error) {
	var list []MarketPrice
	if _, err := c.get(0, "/markets/prices/", &list); err != nil {
		return nil, err
	}
	out := make(map[int64]MarketPrice, len(list))
	for _, p := range list {
		out[p.TypeID] = p
	}
	return out, nil
}

// ── industry / market ────────────────────────────────────────────────

// IndustryJob carries the full ESI job payload. Display-only fields use
// json names that never occur in ESI responses, so decoding is
// unaffected but they survive marshalling into the details modal.
type IndustryJob struct {
	JobID          int64     `json:"job_id"`
	ActivityID     int       `json:"activity_id"`
	Activity       string    `json:"activity_name"`
	BlueprintID    int64     `json:"blueprint_id"`
	BlueprintType  int64     `json:"blueprint_type_id"`
	BlueprintName  string    `json:"blueprint_name"`
	ProductTypeID  int64     `json:"product_type_id"`
	ProductName    string    `json:"product_name"`
	Runs           int       `json:"runs"`
	LicensedRuns   int       `json:"licensed_runs"`
	Probability    float64   `json:"probability"`
	Cost           float64   `json:"cost"`
	Duration       int64     `json:"duration"`
	Status         string    `json:"status"`
	StartDate      time.Time `json:"start_date"`
	EndDate        time.Time `json:"end_date"`
	PauseDate      time.Time `json:"pause_date"`
	CompletedDate  time.Time `json:"completed_date"`
	SuccessfulRuns int       `json:"successful_runs"`
	FacilityID     int64     `json:"facility_id"`
	Facility       string    `json:"facility_name"`
}

var activityNames = map[int]string{
	1: "Производство", 3: "Исследование TE", 4: "Исследование ME",
	5: "Копирование", 8: "Инвент", 9: "Реакции", 11: "Реакции",
}

// fillJobNames resolves blueprint/product/facility names and the
// activity label. Structure names need the authed structures endpoint —
// /universe/names/ rejects structure ids.
func (c *Client) fillJobNames(characterID int64, jobs []*IndustryJob) {
	var ids []int64
	structIDs := map[int64]string{}
	for _, j := range jobs {
		ids = append(ids, j.BlueprintType, j.ProductTypeID)
		if j.FacilityID >= 1_000_000_000_000 {
			structIDs[j.FacilityID] = ""
		} else {
			ids = append(ids, j.FacilityID)
		}
	}
	names := c.Names(ids)

	for sid := range structIDs {
		var st struct {
			Name string `json:"name"`
		}
		if _, err := c.get(characterID, fmt.Sprintf("/universe/structures/%d/", sid), &st); err == nil && st.Name != "" {
			structIDs[sid] = st.Name
		} else {
			structIDs[sid] = fmt.Sprintf("Структура %d", sid)
		}
	}

	for _, j := range jobs {
		j.BlueprintName = names[j.BlueprintType]
		j.ProductName = names[j.ProductTypeID]
		if j.FacilityID >= 1_000_000_000_000 {
			j.Facility = structIDs[j.FacilityID]
		} else {
			j.Facility = names[j.FacilityID]
		}
		j.Activity = activityNames[j.ActivityID]
		if j.Activity == "" {
			j.Activity = fmt.Sprintf("Активность %d", j.ActivityID)
		}
	}
}

func (c *Client) IndustryJobs(characterID int64) ([]IndustryJob, error) {
	var jobs []IndustryJob
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/industry/jobs/", characterID), &jobs); err != nil {
		return nil, err
	}
	ptrs := make([]*IndustryJob, len(jobs))
	for i := range jobs {
		ptrs[i] = &jobs[i]
	}
	c.fillJobNames(characterID, ptrs)
	return jobs, nil
}

type MarketOrder struct {
	OrderID      int64   `json:"order_id"`
	TypeID       int64   `json:"type_id"`
	TypeName     string  `json:"-"`
	Price        float64 `json:"price"`
	VolumeRemain int64   `json:"volume_remain"`
	VolumeTotal  int64   `json:"volume_total"`
	IsBuyOrder   bool    `json:"is_buy_order"`
	LocationID   int64   `json:"location_id"`
	LocationName string  `json:"-"`
	Outbid       bool    `json:"-"` // set by the web layer from the order book
	// Issued and Duration let the accounting collector spread a broker fee
	// across the fills that happened after the order was placed or edited.
	// State is only set by /orders/history/ (open on the live endpoint).
	Issued   time.Time `json:"issued"`
	Duration int       `json:"duration"`
	Escrow   float64   `json:"escrow"`
	RegionID int64     `json:"region_id"`
	State    string    `json:"state"` // cancelled|expired, "" while live
}

func (c *Client) MarketOrders(characterID int64) ([]MarketOrder, error) {
	var orders []MarketOrder
	if _, err := c.get(characterID, fmt.Sprintf("/characters/%d/orders/", characterID), &orders); err != nil {
		return nil, err
	}
	var ids []int64
	for _, o := range orders {
		ids = append(ids, o.TypeID, o.LocationID)
	}
	names := c.Names(ids)
	for i := range orders {
		orders[i].TypeName = names[orders[i].TypeID]
		orders[i].LocationName = names[orders[i].LocationID]
	}
	return orders, nil
}

// MarketDepth is the current order book for one type at one location.
type MarketDepth struct {
	Sells []DepthOrder `json:"sells"`
	Buys  []DepthOrder `json:"buys"`
}

type DepthOrder struct {
	OrderID      int64   `json:"order_id"`
	Price        float64 `json:"price"`
	VolumeRemain int64   `json:"volume_remain"`
	IsMine       bool    `json:"is_mine"`
}

// MarketOrdersAt returns the live order book for a type at the given
// station or structure. Stations resolve through their region market;
// structures use the authenticated structure market endpoint.
func (c *Client) MarketOrdersAt(characterID, typeID, locationID int64) (*MarketDepth, error) {
	type rawOrder struct {
		OrderID      int64   `json:"order_id"`
		Price        float64 `json:"price"`
		VolumeRemain int64   `json:"volume_remain"`
		IsBuyOrder   bool    `json:"is_buy_order"`
		LocationID   int64   `json:"location_id"`
		TypeID       int64   `json:"type_id"`
	}
	var raw []rawOrder

	if locationID >= 1_000_000_000_000 {
		// Player structure market (paginated, authenticated).
		page := 1
		for {
			var chunk []rawOrder
			pages, err := c.get(characterID,
				fmt.Sprintf("/markets/structures/%d/?page=%d", locationID, page), &chunk)
			if err != nil {
				return nil, err
			}
			for _, o := range chunk {
				if o.TypeID == typeID {
					raw = append(raw, o)
				}
			}
			if page >= pages {
				break
			}
			page++
		}
	} else {
		regionID, err := c.regionOfStation(locationID)
		if err != nil {
			return nil, err
		}
		page := 1
		for {
			var chunk []rawOrder
			pages, err := c.get(0,
				fmt.Sprintf("/markets/%d/orders/?order_type=all&type_id=%d&page=%d", regionID, typeID, page), &chunk)
			if err != nil {
				return nil, err
			}
			for _, o := range chunk {
				if o.LocationID == locationID {
					raw = append(raw, o)
				}
			}
			if page >= pages {
				break
			}
			page++
		}
	}

	depth := &MarketDepth{}
	for _, o := range raw {
		d := DepthOrder{OrderID: o.OrderID, Price: o.Price, VolumeRemain: o.VolumeRemain}
		if o.IsBuyOrder {
			depth.Buys = append(depth.Buys, d)
		} else {
			depth.Sells = append(depth.Sells, d)
		}
	}
	sort.Slice(depth.Sells, func(i, j int) bool { return depth.Sells[i].Price < depth.Sells[j].Price })
	sort.Slice(depth.Buys, func(i, j int) bool { return depth.Buys[i].Price > depth.Buys[j].Price })
	return depth, nil
}

// regionOfStation walks station → system → constellation → region.
func (c *Client) regionOfStation(stationID int64) (int64, error) {
	var st struct {
		SystemID int64 `json:"system_id"`
	}
	if _, err := c.get(0, fmt.Sprintf("/universe/stations/%d/", stationID), &st); err != nil {
		return 0, err
	}
	return c.regionOfSystem(st.SystemID)
}

func (c *Client) regionOfSystem(systemID int64) (int64, error) {
	var sys struct {
		ConstellationID int64 `json:"constellation_id"`
	}
	if _, err := c.get(0, fmt.Sprintf("/universe/systems/%d/", systemID), &sys); err != nil {
		return 0, err
	}
	var con struct {
		RegionID int64 `json:"region_id"`
	}
	if _, err := c.get(0, fmt.Sprintf("/universe/constellations/%d/", sys.ConstellationID), &con); err != nil {
		return 0, err
	}
	return con.RegionID, nil
}

// regionOfLocation resolves both NPC stations and player structures
// (the latter needs an authed character to read structure info).
func (c *Client) regionOfLocation(characterID, locationID int64) (int64, error) {
	if locationID < 1_000_000_000_000 {
		return c.regionOfStation(locationID)
	}
	var st struct {
		SolarSystemID int64 `json:"solar_system_id"`
	}
	if _, err := c.get(characterID, fmt.Sprintf("/universe/structures/%d/", locationID), &st); err != nil {
		return 0, err
	}
	return c.regionOfSystem(st.SolarSystemID)
}

// HistoryDay is one day of regional market history for a type.
type HistoryDay struct {
	Date       string  `json:"date"`
	Average    float64 `json:"average"`
	Highest    float64 `json:"highest"`
	Lowest     float64 `json:"lowest"`
	Volume     int64   `json:"volume"`
	OrderCount int64   `json:"order_count"`
}

// MarketHistory returns the last `days` days of price/volume history in
// the region of the given location.
func (c *Client) MarketHistory(characterID, typeID, locationID int64, days int) ([]HistoryDay, error) {
	regionID, err := c.regionOfLocation(characterID, locationID)
	if err != nil {
		return nil, err
	}
	var hist []HistoryDay
	if _, err := c.get(0, fmt.Sprintf("/markets/%d/history/?type_id=%d", regionID, typeID), &hist); err != nil {
		return nil, err
	}
	if len(hist) > days {
		hist = hist[len(hist)-days:]
	}
	return hist, nil
}

// ── corporation ──────────────────────────────────────────────────────

// CharacterPublic returns public info: corporation id and name.
func (c *Client) CharacterPublic(characterID int64) (corpID int64, corpName string, err error) {
	var info struct {
		CorporationID int64 `json:"corporation_id"`
	}
	// Public endpoint — no auth needed.
	if _, err = c.get(0, fmt.Sprintf("/characters/%d/", characterID), &info); err != nil {
		return 0, "", err
	}
	names := c.Names([]int64{info.CorporationID})
	return info.CorporationID, names[info.CorporationID], nil
}

// CorporationProjects fetches all corporation projects. The endpoint
// only exists on the new compatibility-dated ESI. The listing is
// cursor-paginated (10 per page, oldest first) and defaults to active
// projects only, so we ask for state=All and walk the "after" cursor;
// the schema is still evolving, so items are decoded generically.
func (c *Client) CorporationProjects(characterID, corporationID int64) ([]map[string]any, error) {
	toList := func(v any) []map[string]any {
		list, ok := v.([]any)
		if !ok {
			return nil
		}
		var out []map[string]any
		for _, item := range list {
			if m, ok := item.(map[string]any); ok {
				out = append(out, m)
			}
		}
		return out
	}

	var merged []map[string]any
	seen := map[string]bool{}
	query := "?state=All"
	for page := 0; page < 50; page++ { // safety cap
		var raw any
		if _, err := c.getCompat(characterID,
			fmt.Sprintf("/corporations/%d/projects%s", corporationID, query), &raw); err != nil {
			if page == 0 {
				return nil, err
			}
			log.Printf("corp projects page %d: %v", page, err)
			break
		}

		m, ok := raw.(map[string]any)
		if !ok {
			// Plain array (older schema) — single page.
			merged = append(merged, toList(raw)...)
			break
		}

		added := 0
		for _, p := range toList(m["projects"]) {
			key := fmt.Sprint(p["id"]) + "/" + fmt.Sprint(p["name"])
			if !seen[key] {
				seen[key] = true
				merged = append(merged, p)
				added++
			}
		}

		cursor, _ := m["cursor"].(map[string]any)
		after, _ := cursor["after"].(string)
		if after == "" || added == 0 {
			break
		}
		query = "?state=All&after=" + url.QueryEscape(after)
	}

	// Newest first for display (RFC3339 sorts lexicographically).
	sort.Slice(merged, func(i, j int) bool {
		return fmt.Sprint(merged[i]["last_modified"]) > fmt.Sprint(merged[j]["last_modified"])
	})
	return merged, nil
}

// CorpIndustryJob is a corporation industry job (requires the Factory
// Manager role in game).
type CorpIndustryJob struct {
	IndustryJob
	InstallerID int64  `json:"installer_id"`
	Installer   string `json:"installer_name"`
}

func (c *Client) CorporationIndustryJobs(characterID, corporationID int64) ([]CorpIndustryJob, error) {
	var jobs []CorpIndustryJob
	if _, err := c.get(characterID, fmt.Sprintf("/corporations/%d/industry/jobs/", corporationID), &jobs); err != nil {
		return nil, err
	}
	ptrs := make([]*IndustryJob, len(jobs))
	ids := make([]int64, len(jobs))
	for i := range jobs {
		ptrs[i] = &jobs[i].IndustryJob
		ids[i] = jobs[i].InstallerID
	}
	c.fillJobNames(characterID, ptrs)
	names := c.Names(ids)
	for i := range jobs {
		jobs[i].Installer = names[jobs[i].InstallerID]
	}
	return jobs, nil
}

// CorpInfo is public corporation information.
type CorpInfo struct {
	Name        string  `json:"name"`
	Ticker      string  `json:"ticker"`
	MemberCount int     `json:"member_count"`
	TaxRate     float64 `json:"tax_rate"`
	AllianceID  int64   `json:"alliance_id"`
	CEOID       int64   `json:"ceo_id"`
	CEOName     string  `json:"-"`
	Alliance    string  `json:"-"`
}

// TaxRatePct returns the tax rate as percents for display.
func (i *CorpInfo) TaxRatePct() float64 { return i.TaxRate * 100 }

func (c *Client) CorporationInfo(corporationID int64) (*CorpInfo, error) {
	var info CorpInfo
	if _, err := c.get(0, fmt.Sprintf("/corporations/%d/", corporationID), &info); err != nil {
		return nil, err
	}
	names := c.Names([]int64{info.CEOID, info.AllianceID})
	info.CEOName = names[info.CEOID]
	info.Alliance = names[info.AllianceID]
	return &info, nil
}

// CorpWallet is one corporation wallet division balance.
type CorpWallet struct {
	Division int     `json:"division"`
	Balance  float64 `json:"balance"`
}

// CorporationWalletNames returns custom wallet division names
// (needs the Director role); absent or empty names are omitted so the
// caller can fall back to generic labels.
func (c *Client) CorporationWalletNames(characterID, corporationID int64) (map[int]string, error) {
	var out struct {
		Wallet []struct {
			Division int    `json:"division"`
			Name     string `json:"name"`
		} `json:"wallet"`
	}
	if _, err := c.get(characterID, fmt.Sprintf("/corporations/%d/divisions/", corporationID), &out); err != nil {
		return nil, err
	}
	names := map[int]string{}
	for _, d := range out.Wallet {
		if d.Name != "" {
			names[d.Division] = d.Name
		}
	}
	return names, nil
}

// CorporationWalletJournal returns the wallet journal of one division
// (first page, newest first). Needs the Accountant role.
func (c *Client) CorporationWalletJournal(characterID, corporationID int64, division int) ([]JournalEntry, error) {
	var out []JournalEntry
	_, err := c.get(characterID,
		fmt.Sprintf("/corporations/%d/wallets/%d/journal/", corporationID, division), &out)
	return out, err
}

// CorporationWalletTransactions returns market transactions of one
// division with resolved names. Needs the Accountant role.
func (c *Client) CorporationWalletTransactions(characterID, corporationID int64, division int) ([]Transaction, error) {
	var out []Transaction
	if _, err := c.get(characterID,
		fmt.Sprintf("/corporations/%d/wallets/%d/transactions/", corporationID, division), &out); err != nil {
		return nil, err
	}
	var ids []int64
	for _, t := range out {
		ids = append(ids, t.TypeID, t.LocationID)
	}
	names := c.Names(ids)
	for i := range out {
		out[i].TypeName = names[out[i].TypeID]
		out[i].LocationName = names[out[i].LocationID]
	}
	return out, nil
}

// CorporationWallets requires the Accountant role in game.
func (c *Client) CorporationWallets(characterID, corporationID int64) ([]CorpWallet, error) {
	var wallets []CorpWallet
	_, err := c.get(characterID, fmt.Sprintf("/corporations/%d/wallets/", corporationID), &wallets)
	return wallets, err
}

// ── misc actions ─────────────────────────────────────────────────────

// ResolveSystem converts a solar system name to its id via /universe/ids/.
func (c *Client) ResolveSystem(name string) (int64, error) {
	return c.resolveName(name, "systems", "система")
}

var (
	// "Pator V (Vakir)" → strip "(Vakir)", then the planet numeral "V".
	parenTail = regexp.MustCompile(`\s*\([^)]*\)$`)
	romanTail = regexp.MustCompile(`\s+[IVXLCDM]+$`)
	digitsRe  = regexp.MustCompile(`\d+`)
)

// CleanPastedName strips what the game client appends when a location name
// is copied out of it: a trailing asterisk and stray spaces ("Leurtmar* ").
func CleanPastedName(s string) string {
	return strings.TrimSpace(strings.TrimRight(strings.TrimSpace(s), "* \t\u00a0"))
}

// ResolveDestination turns a pasted destination — a solar system or an NPC
// station, copied from a client in any language — into an id SetWaypoint
// accepts, plus the canonical name of what was actually resolved.
//
// /universe/ids/ only knows English names, so a station pasted from a
// localized client ("Pator V (Vakir) - Центр снабжения Republic Fleet")
// resolves in two hops: the "Pator V (Vakir)" prefix and the moon number
// are the same in every locale, which pins the system and narrows its
// station list; corp names in the localized tail keep their Latin words
// ("Republic Fleet"), which breaks ties between stations sharing a planet.
func (c *Client) ResolveDestination(raw string) (int64, string, error) {
	name := CleanPastedName(raw)
	if name == "" {
		return 0, "", fmt.Errorf("пустое название")
	}
	if id, _ := c.lookupExact(name); id != 0 {
		return id, name, nil // exact hit, English or plain system name
	}
	seg := strings.Split(name, " - ")
	if len(seg) < 2 {
		return 0, "", fmt.Errorf("система %q не найдена", name)
	}
	place := strings.TrimSpace(seg[0])
	sysName := strings.TrimSpace(romanTail.ReplaceAllString(parenTail.ReplaceAllString(place, ""), ""))
	sysID, err := c.ResolveSystem(sysName)
	if err != nil {
		return 0, "", fmt.Errorf("станция %q не найдена (и система %q тоже)", name, sysName)
	}

	var sys struct {
		Stations []int64 `json:"stations"`
	}
	if err := c.publicGet("/universe/systems/"+strconv.FormatInt(sysID, 10)+"/", &sys); err != nil {
		return 0, "", err
	}
	wantMoon := middleNumber(seg)
	best, bestScore := "", -1
	var bestID int64
	for _, sid := range sys.Stations {
		var st struct {
			Name string `json:"name"`
		}
		if err := c.publicGet("/universe/stations/"+strconv.FormatInt(sid, 10)+"/", &st); err != nil {
			continue
		}
		eseg := strings.Split(st.Name, " - ")
		if !strings.EqualFold(strings.TrimSpace(eseg[0]), place) || middleNumber(eseg) != wantMoon {
			continue
		}
		score := tokenOverlap(seg[len(seg)-1], eseg[len(eseg)-1])
		if score > bestScore {
			best, bestScore, bestID = st.Name, score, sid
		}
	}
	if bestID != 0 {
		return bestID, best, nil
	}
	// The place parsed but no station matched: route to the system at least.
	return sysID, sysName + " (станция не опознана, маршрут до системы)", nil
}

// lookupExact asks /universe/ids/ for the name and takes a system or an
// NPC station, whichever matches. English names only — that's all it knows.
func (c *Client) lookupExact(name string) (int64, string) {
	payload, _ := json.Marshal([]string{name})
	req, err := http.NewRequest("POST", baseURL+"/universe/ids/", bytes.NewReader(payload))
	if err != nil {
		return 0, ""
	}
	req.Header.Set("User-Agent", c.st.userAgent)
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.st.http.Do(req)
	if err != nil {
		return 0, ""
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return 0, ""
	}
	var out map[string][]struct {
		ID int64 `json:"id"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return 0, ""
	}
	for _, bucket := range []string{"systems", "stations"} {
		if len(out[bucket]) > 0 {
			return out[bucket][0].ID, bucket
		}
	}
	return 0, ""
}

// middleNumber pulls the moon number out of "Sys IV - Moon 3 - Station":
// the numeral in the middle segments is locale-independent («Луна 3»).
func middleNumber(seg []string) string {
	for _, s := range seg[1 : len(seg)-1] {
		if m := digitsRe.FindString(s); m != "" {
			return m
		}
	}
	return ""
}

// tokenOverlap counts words two station-name tails share, case-insensitively.
func tokenOverlap(a, b string) int {
	set := map[string]bool{}
	for _, w := range strings.Fields(strings.ToLower(a)) {
		set[w] = true
	}
	n := 0
	for _, w := range strings.Fields(strings.ToLower(b)) {
		if set[w] {
			n++
		}
	}
	return n
}

// publicGet fetches an unauthenticated ESI endpoint.
func (c *Client) publicGet(path string, out any) error {
	req, err := http.NewRequest("GET", baseURL+path, nil)
	if err != nil {
		return err
	}
	req.Header.Set("User-Agent", c.st.userAgent)
	resp, err := c.st.http.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: %s", path, resp.Status)
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

// ResolveCharacter converts a character name to its id (exact match).
func (c *Client) ResolveCharacter(name string) (int64, error) {
	return c.resolveName(name, "characters", "персонаж")
}

// resolveName looks a name up in one bucket of /universe/ids/.
func (c *Client) resolveName(name, bucket, what string) (int64, error) {
	payload, _ := json.Marshal([]string{name})
	req, err := http.NewRequest("POST", baseURL+"/universe/ids/", bytes.NewReader(payload))
	if err != nil {
		return 0, err
	}
	req.Header.Set("User-Agent", c.st.userAgent)
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.st.http.Do(req)
	if err != nil {
		return 0, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return 0, fmt.Errorf("resolve %q: %s", name, resp.Status)
	}
	var out map[string][]struct {
		ID   int64  `json:"id"`
		Name string `json:"name"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return 0, err
	}
	if len(out[bucket]) == 0 {
		return 0, fmt.Errorf("%s %q не найден(а)", what, name)
	}
	return out[bucket][0].ID, nil
}

// SetWaypoint sets an autopilot waypoint in the game client of the
// character (the character must be online).
func (c *Client) SetWaypoint(characterID, destinationID int64, clearOthers bool) error {
	path := fmt.Sprintf("/ui/autopilot/waypoint/?add_to_beginning=false&clear_other_waypoints=%t&destination_id=%d",
		clearOthers, destinationID)
	return c.post(characterID, path, nil)
}

// ── assets ───────────────────────────────────────────────────────────

type rawAsset struct {
	ItemID     int64 `json:"item_id"`
	TypeID     int64 `json:"type_id"`
	LocationID int64 `json:"location_id"`
	Quantity   int64 `json:"quantity"`
	// ESI only sets this flag for blueprint copies.
	IsBlueprintCopy bool `json:"is_blueprint_copy"`
}

type AssetItem struct {
	TypeID   int64
	TypeName string
	Quantity int64
	IsCopy   bool // blueprint copy — needs the "bpc" artwork
	// Research levels, filled in for blueprints so the item card opens
	// with the real numbers of that stack.
	ME   int
	TE   int
	Runs int64 // -1 for originals
}

type LocationAssets struct {
	LocationID   int64
	LocationName string
	Total        int64
	Items        []AssetItem
}

func (c *Client) assetPages(characterID int64, pathFmt string) ([]rawAsset, error) {
	var all []rawAsset
	page := 1
	for {
		var chunk []rawAsset
		pages, err := c.get(characterID, fmt.Sprintf(pathFmt, page), &chunk)
		if err != nil {
			return nil, err
		}
		all = append(all, chunk...)
		if page >= pages {
			return all, nil
		}
		page++
	}
}

// groupAssets rolls nested items (containers, ship holds) up to their
// real root location and aggregates quantities by type. bpByItem adds
// per-item blueprint research levels (may be nil).
func (c *Client) groupAssets(characterID int64, raw []rawAsset, bpByItem map[int64]OwnedBlueprint) []LocationAssets {
	byItem := map[int64]rawAsset{}
	for _, a := range raw {
		byItem[a.ItemID] = a
	}
	rootOf := func(a rawAsset) int64 {
		loc := a.LocationID
		for depth := 0; depth < 32; depth++ {
			parent, ok := byItem[loc]
			if !ok {
				return loc
			}
			loc = parent.LocationID
		}
		return loc
	}

	// Blueprints are grouped by their research levels too: copies and
	// originals, and differently researched stacks, are distinct items.
	type assetKey struct {
		typeID int64
		isCopy bool
		me, te int
		runs   int64
	}
	counts := map[int64]map[assetKey]int64{} // root location -> key -> qty
	for _, a := range raw {
		root := rootOf(a)
		if counts[root] == nil {
			counts[root] = map[assetKey]int64{}
		}
		qty := a.Quantity
		if qty == 0 {
			qty = 1
		}
		k := assetKey{typeID: a.TypeID, isCopy: a.IsBlueprintCopy, runs: -1}
		if bp, ok := bpByItem[a.ItemID]; ok {
			k.me, k.te, k.runs, k.isCopy = bp.ME, bp.TE, bp.Runs, bp.IsCopy()
		}
		counts[root][k] += qty
	}

	// Resolve names: types + station/system locations via /universe/names/,
	// structures via the authed structures endpoint.
	var nameIDs []int64
	structIDs := map[int64]string{}
	for loc, types := range counts {
		if loc >= 1_000_000_000_000 {
			structIDs[loc] = ""
		} else {
			nameIDs = append(nameIDs, loc)
		}
		for k := range types {
			nameIDs = append(nameIDs, k.typeID)
		}
	}
	names := c.Names(nameIDs)
	for sid := range structIDs {
		var st struct {
			Name string `json:"name"`
		}
		if _, err := c.get(characterID, fmt.Sprintf("/universe/structures/%d/", sid), &st); err == nil && st.Name != "" {
			structIDs[sid] = st.Name
		} else {
			structIDs[sid] = fmt.Sprintf("Структура %d", sid)
		}
	}

	var out []LocationAssets
	for loc, types := range counts {
		la := LocationAssets{LocationID: loc}
		if loc >= 1_000_000_000_000 {
			la.LocationName = structIDs[loc]
		} else if n := names[loc]; n != "" {
			la.LocationName = n
		} else {
			la.LocationName = fmt.Sprintf("Локация %d", loc)
		}
		for k, q := range types {
			name := names[k.typeID]
			if name == "" {
				name = fmt.Sprintf("Тип %d", k.typeID)
			}
			la.Items = append(la.Items, AssetItem{
				TypeID: k.typeID, TypeName: name, Quantity: q, IsCopy: k.isCopy,
				ME: k.me, TE: k.te, Runs: k.runs,
			})
			la.Total += q
		}
		sort.Slice(la.Items, func(i, j int) bool {
			if la.Items[i].Quantity != la.Items[j].Quantity {
				return la.Items[i].Quantity > la.Items[j].Quantity
			}
			return la.Items[i].TypeName < la.Items[j].TypeName
		})
		out = append(out, la)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Total > out[j].Total })
	return out
}

// CharacterAssets returns the character's assets grouped by location,
// with blueprint research levels merged in.
func (c *Client) CharacterAssets(characterID int64) ([]LocationAssets, error) {
	raw, err := c.assetPages(characterID, fmt.Sprintf("/characters/%d/assets/?page=%%d", characterID))
	if err != nil {
		return nil, err
	}
	bpByItem := map[int64]OwnedBlueprint{}
	if bps, err := c.CharacterBlueprints(characterID); err == nil {
		for _, b := range bps {
			bpByItem[b.ItemID] = b
		}
	}
	return c.groupAssets(characterID, raw, bpByItem), nil
}

// CorporationAssets returns corp assets grouped by location (needs the
// Director role in game).
func (c *Client) CorporationAssets(characterID, corporationID int64) ([]LocationAssets, error) {
	raw, err := c.assetPages(characterID, fmt.Sprintf("/corporations/%d/assets/?page=%%d", corporationID))
	if err != nil {
		return nil, err
	}
	bpByItem := map[int64]OwnedBlueprint{}
	if bps, err := c.CorporationBlueprints(characterID, corporationID); err == nil {
		for _, b := range bps {
			bpByItem[b.ItemID] = b
		}
	}
	return c.groupAssets(characterID, raw, bpByItem), nil
}

// CorporationBlueprints lists corporation blueprints (Director role).
func (c *Client) CorporationBlueprints(characterID, corporationID int64) ([]OwnedBlueprint, error) {
	var all []OwnedBlueprint
	page := 1
	for {
		var chunk []OwnedBlueprint
		pages, err := c.get(characterID,
			fmt.Sprintf("/corporations/%d/blueprints/?page=%d", corporationID, page), &chunk)
		if err != nil {
			return nil, err
		}
		all = append(all, chunk...)
		if page >= pages {
			return all, nil
		}
		page++
	}
}

// AssetCount fetches all asset pages and returns the total item count.
func (c *Client) AssetCount(characterID int64) (int, error) {
	total := 0
	page := 1
	for {
		var assets []struct {
			ItemID int64 `json:"item_id"`
		}
		pages, err := c.get(characterID, fmt.Sprintf("/characters/%d/assets/?page=%d", characterID, page), &assets)
		if err != nil {
			return total, err
		}
		total += len(assets)
		if page >= pages {
			return total, nil
		}
		page++
	}
}
